version: '3.1'

services:
  reservation-app:
    container_name: reservation-app
    image: postrgresslearn/reservation-app:latest

    restart: always
    ports:
      - 8001:8001

    volumes:
      - ./credentials:/usr/app/credentials

    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/quick-table

    depends_on:
      - mysql

  mysql:
    container_name: mysql
    restart: always
    image: mysql

    ports:
      - 3306:3306

    environment:
      MYSQL_DATABASE: quick-table 
      MYSQL_USER: quick-table
      MYSQL_PASS: yummy
      MYSQL_ROOT_PASSWORD: super-yummy

    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    container_name: mysql-adminer
    image: adminer
    restart: always
    ports:
      - 6000:8080

